theme: jekyll-theme-slate

show_downloads: true
github:
  chrome_url: https://chrome.google.com/webstore/detail/scholarenhancer/nddafijbmgolhdgmpedfpadenjlemdlc
  firefox_url: https://addons.mozilla.org/en-US/firefox/addon/scholarenhancer
